version: '3.6'

services:

    server:
        container_name: server_box
        build:
            context: ./server
            dockerfile: ./Dockerfile
        expose:
            - ${WEB_SERVER_PORT}
        ports:
            - ${WEB_SERVER_PORT}:${WEB_SERVER_PORT}
        working_dir: /src
        volumes:
            - ./server:/src
        command: uvicorn app:app --host ${WEB_SERVER_HOST} --port ${WEB_SERVER_PORT} --reload
    client:
        container_name: client_box
        build:
            context: ./client
            dockerfile: ./Dockerfile
        environment:
            WEB_CLIENT_PORT: ${WEB_CLIENT_PORT}
            PUBLIC_API_HOST: ${PUBLIC_API_HOST}
            INTERNAL_API_HOST: 'http://server:8080'
        ports:
            - ${WEB_CLIENT_PORT}:${WEB_CLIENT_PORT}
        links:
            - server
        volumes:
            - ./client:/src
        working_dir: /src
        command: yarn run dev
